### ISSUE TITLE
Code Exit: 1 Crash Error

### ISSUE THREAD

**Issue by OneMonkey13** [MehVahdJukaar/Christmas#63]
I've been attempting to run this Mod with Forge 1.20.1 and the mods newest 1.20.1 release and my Minecraft just continues to crash over and over. Once I remove the mod I'm able to run Minecraft perfectly fine.  I had no other mods installed.

**Comment by MehVahdJukaar** [comment]
send latest.log. exit code 1 doesnt mean anything

**Comment by OneMonkey13** [comment]
[11Nov2023 22:09:52.528] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, OneMonkey, --version, 1.19.2-forge-43.3.5, --gameDir, C:\Users\OneMo\AppData\Roaming\.minecraft, --assetsDir, C:\Users\OneMo\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, dab107191c3e485297cb5ca909b3f5cc, --accessToken, ????????, --clientId, MmZlZWRlMjMtN2FlNS00MDQyLTk4NjEtM2ZiMmQ1ZDM1NDJk, --xuid, 2535409417738513, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.3.5, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[11Nov2023 22:09:52.532] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.8 by Microsoft; OS Windows 10 arch amd64 version 10.0
[11Nov2023 22:09:52.665] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/OneMo/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2397!/ Service=ModLauncher Env=CLIENT
[11Nov2023 22:09:52.948] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\OneMo\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19.2-43.3.5\fmlcore-1.19.2-43.3.5.jar is missing mods.toml file
[11Nov2023 22:09:52.952] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\OneMo\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.3.5\javafmllanguage-1.19.2-43.3.5.jar is missing mods.toml file
[11Nov2023 22:09:52.956] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\OneMo\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.3.5\lowcodelanguage-1.19.2-43.3.5.jar is missing mods.toml file
[11Nov2023 22:09:52.960] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\OneMo\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19.2-43.3.5\mclanguage-1.19.2-43.3.5.jar is missing mods.toml file
[11Nov2023 22:09:53.030] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[11Nov2023 22:09:53.093] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'moonlight', Requested by: 'snowyspirit', Expected range: '[1.19-2.0.16,)', Actual version: '[MISSING]'
[11Nov2023 22:09:53.970] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.2-forge-43.3.5, --gameDir, C:\Users\OneMo\AppData\Roaming\.minecraft, --assetsDir, C:\Users\OneMo\AppData\Roaming\.minecraft\assets, --uuid, dab107191c3e485297cb5ca909b3f5cc, --username, OneMonkey, --assetIndex, 1.19, --accessToken, ????????, --clientId, MmZlZWRlMjMtN2FlNS00MDQyLTk4NjEtM2ZiMmQ1ZDM1NDJk, --xuid, 2535409417738513, --userType, msa, --versionType, release]
[11Nov2023 22:09:54.167] [main/WARN] [mixin/]: Error loading class: net/mehvahdjukaar/moonlight/api/block/WaterBlock (java.lang.ClassNotFoundException: net.mehvahdjukaar.moonlight.api.block.WaterBlock)
[11Nov2023 22:09:54.173] [main/ERROR] [mixin/]: snowyspirit.mixins.json:SelfGlowLightsBlockMixin: Super class 'net.minecraft.world.level.block.Block' of SelfGlowLightsBlockMixin was not found in the hierarchy of target class 'net/mehvahdjukaar/snowyspirit/common/block/GlowLightsBlock'
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Super class 'net.minecraft.world.level.block.Block' of SelfGlowLightsBlockMixin was not found in the hierarchy of target class 'net/mehvahdjukaar/snowyspirit/common/block/GlowLightsBlock'
	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard.validate(MixinInfo.java:593) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:327) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:913) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:801) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:567) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637) ~[?:?]
	at java.lang.Class.forName(Class.java:545) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[11Nov2023 22:09:57.358] [pool-3-thread-1/INFO] [net.minecraft.util.datafix.DataFixers/]: Building unoptimized datafixer
[11Nov2023 22:09:58.900] [pool-3-thread-1/WARN] [mixin/]: Error loading class: net/mehvahdjukaar/moonlight/api/entity/IControllableVehicle (java.lang.ClassNotFoundException: net.mehvahdjukaar.moonlight.api.entity.IControllableVehicle)
[11Nov2023 22:09:58.902] [pool-3-thread-1/WARN] [mixin/]: Error loading class: net/mehvahdjukaar/moonlight/api/entity/IExtraClientSpawnData (java.lang.ClassNotFoundException: net.mehvahdjukaar.moonlight.api.entity.IExtraClientSpawnData)
[11Nov2023 22:09:58.904] [pool-3-thread-1/WARN] [mixin/]: Error loading class: net/mehvahdjukaar/moonlight/api/platform/PlatformHelper (java.lang.ClassNotFoundException: net.mehvahdjukaar.moonlight.api.platform.PlatformHelper)

*Sure thing. My apologies.

**Comment by OneMonkey13** [comment]
[latest.log](https://github.com/MehVahdJukaar/SnowySpirit/files/13327483/latest.log)


Sure thing! c:

**Comment by OneMonkey13** [comment]
hey! nvm wait I see what I did wrong. I didn't have the Moonlight Lib. Downloaded that and fixed my issue!
